[package]
name = "sequence_align_rs"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
sequence_align = { path = "rust" }
#
#[workspace]
#members = ["sequence_align"]
#default-members = ["sequence_align"]
#resolver = "2"
